export const DESIGN_SIZE = {
  width: 1396,
  height: 785,
};

export const SITE_RENDER_SCALE = 0.75;
export const CORRUPTION_PADDING = 22;
export const CORRUPTION_FEATHER = 72;
export const CORRUPTION_SAFE_GAP = 14;

export const SITES = [
  { id: "site_17", label: "入口", y: 92, x: 1120, width: 317, height: 191, sequence: 1, initialCorrupted: true },
  { id: "site_13", label: "早八", y: 220, x: 704, width: 271, height: 125, sequence: 2, battle: "stage_13" },
  { id: "site_09", label: "事件：大礼堂", y: 296, x: 453, width: 345, height: 154, sequence: 3, event: "event_auditorium" },
  { id: "site_20", label: "抖腿前桌", y: 135, x: 229, width: 342, height: 173, sequence: 4, battle: "stage_20" },
  { id: "site_22", label: "事件：85km", y: 603, x: 194, width: 309, height: 213, sequence: 5, event: "event_85km" },
  { id: "site_08", label: "签到二维码", y: 521, x: 413, width: 221, height: 150, sequence: 6, battle: "stage_08" },
  { id: "site_04", label: "舍敌组合", y: 621, x: 686, width: 211, height: 155, sequence: 7, battle: "stage_04" },
  { id: "site_18", label: "事件：博雅塔", y: 493, x: 903, width: 316, height: 217, sequence: 8, event: "event_boya_tower" },
  { id: "site_23", label: "理想的灵柩", y: 349, x: 1022, width: 438, height: 360, sequence: 9, battle: "stage_23", iconScale: 0.75 },
  { id: "site_01", label: "图书馆（商店）", y: 384, x: 697, width: 371, height: 162, shop: true, shopUnlockAfter: "site_13" },
];

export const MAP_CORRUPTION_CLEARINGS = [
  [
    { x: 572, y: 320 },
    { x: 660, y: 292 },
    { x: 790, y: 304 },
    { x: 848, y: 368 },
    { x: 820, y: 454 },
    { x: 704, y: 494 },
    { x: 592, y: 458 },
    { x: 544, y: 386 },
  ],
];

export const MAP_CORRUPTION_STAGES = [
  {
    id: "site_17",
    clip: [
      { x: 1006, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 198 },
      { x: 1302, y: 238 },
      { x: 1192, y: 222 },
      { x: 1080, y: 190 },
      { x: 980, y: 110 },
    ],
    edge: [
      { x: 1396, y: 198 },
      { x: 1302, y: 238 },
      { x: 1192, y: 222 },
      { x: 1080, y: 190 },
      { x: 980, y: 110 },
      { x: 1006, y: 0 },
    ],
  },
  {
    id: "site_13",
    clip: [
      { x: 520, y: 0 },
      { x: 930, y: 0 },
      { x: 1032, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 238 },
      { x: 1292, y: 292 },
      { x: 1110, y: 256 },
      { x: 936, y: 282 },
      { x: 764, y: 338 },
      { x: 622, y: 304 },
      { x: 548, y: 184 },
    ],
    edge: [
      { x: 1396, y: 238 },
      { x: 1292, y: 292 },
      { x: 1110, y: 256 },
      { x: 936, y: 282 },
      { x: 764, y: 338 },
      { x: 622, y: 304 },
      { x: 548, y: 184 },
      { x: 520, y: 0 },
    ],
  },
  {
    id: "site_09",
    clip: [
      { x: 302, y: 0 },
      { x: 548, y: 0 },
      { x: 684, y: 0 },
      { x: 930, y: 0 },
      { x: 1032, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 244 },
      { x: 1288, y: 302 },
      { x: 1110, y: 262 },
      { x: 934, y: 302 },
      { x: 768, y: 354 },
      { x: 628, y: 360 },
      { x: 502, y: 414 },
      { x: 350, y: 372 },
      { x: 312, y: 206 },
    ],
    edge: [
      { x: 1396, y: 244 },
      { x: 1288, y: 302 },
      { x: 1110, y: 262 },
      { x: 934, y: 302 },
      { x: 768, y: 354 },
      { x: 628, y: 360 },
      { x: 502, y: 414 },
      { x: 350, y: 372 },
      { x: 312, y: 206 },
      { x: 302, y: 0 },
    ],
  },
  {
    id: "site_20",
    clip: [
      { x: 0, y: 0 },
      { x: 1032, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 934, y: 290 },
      { x: 768, y: 336 },
      { x: 628, y: 344 },
      { x: 502, y: 402 },
      { x: 330, y: 388 },
      { x: 178, y: 308 },
      { x: 0, y: 246 },
    ],
    edge: [
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 934, y: 290 },
      { x: 768, y: 336 },
      { x: 628, y: 344 },
      { x: 502, y: 402 },
      { x: 330, y: 388 },
      { x: 178, y: 308 },
      { x: 0, y: 246 },
    ],
  },
  {
    id: "site_22",
    clip: [
      { x: 0, y: 0 },
      { x: 1032, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 934, y: 290 },
      { x: 768, y: 336 },
      { x: 628, y: 344 },
      { x: 502, y: 402 },
      { x: 350, y: 392 },
      { x: 276, y: 438 },
      { x: 292, y: 565 },
      { x: 330, y: 720 },
      { x: 220, y: 785 },
      { x: 0, y: 785 },
    ],
    edge: [
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 934, y: 290 },
      { x: 768, y: 336 },
      { x: 628, y: 344 },
      { x: 502, y: 402 },
      { x: 350, y: 392 },
      { x: 276, y: 438 },
      { x: 292, y: 565 },
      { x: 330, y: 720 },
      { x: 220, y: 785 },
    ],
  },
  {
    id: "site_08",
    clip: [
      { x: 0, y: 0 },
      { x: 1032, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 934, y: 290 },
      { x: 768, y: 336 },
      { x: 628, y: 344 },
      { x: 502, y: 402 },
      { x: 548, y: 520 },
      { x: 560, y: 652 },
      { x: 480, y: 735 },
      { x: 300, y: 785 },
      { x: 0, y: 785 },
    ],
    edge: [
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 934, y: 290 },
      { x: 768, y: 336 },
      { x: 628, y: 344 },
      { x: 502, y: 402 },
      { x: 548, y: 520 },
      { x: 560, y: 652 },
      { x: 480, y: 735 },
      { x: 300, y: 785 },
    ],
  },
  {
    id: "site_04",
    clip: [
      { x: 0, y: 0 },
      { x: 1032, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 934, y: 290 },
      { x: 768, y: 336 },
      { x: 628, y: 344 },
      { x: 502, y: 402 },
      { x: 548, y: 520 },
      { x: 732, y: 548 },
      { x: 818, y: 650 },
      { x: 760, y: 785 },
      { x: 0, y: 785 },
    ],
    edge: [
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 934, y: 290 },
      { x: 768, y: 336 },
      { x: 628, y: 344 },
      { x: 502, y: 402 },
      { x: 548, y: 520 },
      { x: 732, y: 548 },
      { x: 818, y: 650 },
      { x: 760, y: 785 },
    ],
  },
  {
    id: "site_18",
    clip: [
      { x: 0, y: 0 },
      { x: 1032, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 1004, y: 366 },
      { x: 1118, y: 452 },
      { x: 1168, y: 574 },
      { x: 1212, y: 710 },
      { x: 1194, y: 785 },
      { x: 0, y: 785 },
    ],
    edge: [
      { x: 1396, y: 218 },
      { x: 1288, y: 282 },
      { x: 1110, y: 248 },
      { x: 1004, y: 366 },
      { x: 1118, y: 452 },
      { x: 1168, y: 574 },
      { x: 1212, y: 710 },
      { x: 1194, y: 785 },
    ],
  },
  {
    id: "site_23",
    clip: [
      { x: 0, y: 0 },
      { x: 1396, y: 0 },
      { x: 1396, y: 785 },
      { x: 0, y: 785 },
    ],
    edge: [
      { x: 542, y: 302 },
      { x: 650, y: 268 },
      { x: 812, y: 284 },
      { x: 880, y: 366 },
      { x: 846, y: 478 },
      { x: 704, y: 520 },
      { x: 570, y: 474 },
      { x: 512, y: 386 },
      { x: 542, y: 302 },
    ],
  },
];

export const CARD_DEFS = {
  "3.92": {
    name: "3.92",
    type: "attack",
    cost: 0,
    text: "精神低于 5 时可打出。造成 3 点基础伤害，此牌受到的力量加成为两倍。",
    tags: [],
  },
  talk: {
    name: "谈笑风生",
    type: "attack",
    cost: 0,
    text: "造成 5 伤害。精神至少 6：追加 5 伤害。",
    tags: [],
  },
  persuade: {
    name: "好言相劝",
    type: "attack",
    cost: 1,
    text: "造成 7 伤害。获得 1 力量。",
    tags: [],
  },
  temporary: {
    name: "暂",
    type: "skill",
    cost: 5,
    dynamicCost: "mentalRecovery",
    text: "本回合敌人对玩家造成的伤害和施加的效果无效。本回合每实际回复 1 次精神，此牌费用 -1，最多降低 3 点。",
    tags: [],
  },
  one_tenth: {
    name: "1/10",
    type: "attack",
    cost: 1,
    text: "造成 4 伤害。施加 2 注视，将 2 张【循证】加入抽牌堆。注视达到 10：清空注视，造成 50 无法被防御的伤害。",
    tags: [],
  },
  evidence: {
    name: "循证",
    type: "skill",
    cost: 0,
    text: "施加 2 注视。精神高于 6：额外施加 1 注视。",
    tags: ["消耗"],
    exhaust: true,
  },
  insight: {
    name: "洞见",
    type: "skill",
    cost: 1,
    text: "获得 2 层随机增益。精神至少 8：改为 3 层。可能获得：力量 +1、敏捷 +1、或每回合抽牌 +1。",
    tags: ["保留", "消耗"],
    retain: true,
    exhaust: true,
  },
  breathe: {
    name: "深呼吸",
    type: "skill",
    cost: 0,
    text: "回复 2 精神。下回合少抽 1 张牌。",
    tags: ["消耗"],
    exhaust: true,
  },
  boya: {
    name: "博雅塔前您博雅",
    type: "skill",
    cost: 0,
    text: "获得 6 防御。暑假：回复 2 精神。",
    tags: [],
  },
  reflect: {
    name: "反省",
    type: "skill",
    cost: 0,
    text: "抽 2 张牌。暑假：额外抽 1 张。",
    tags: [],
  },
  retreat: {
    name: "以退为进",
    type: "skill",
    cost: 0,
    text: "抽 2 张牌，然后弃 1 张手牌。若弃掉攻击牌，回复 1 精神。",
    tags: [],
  },
  retake: {
    name: "重修",
    type: "skill",
    cost: 0,
    text: "弃掉所有剩余手牌，再抽取相同数量的牌。",
    tags: ["消耗"],
    exhaust: true,
  },
  torment: {
    name: "煎熬",
    type: "defense",
    cost: 1,
    text: "获得 11 防御。",
    tags: [],
  },
  rest: {
    name: "休整",
    type: "defense",
    cost: 0,
    text: "获得 6 防御。暑假：额外获得 6 防御。",
    tags: [],
  },
  call: {
    name: "呼唤",
    type: "skill",
    cost: 1,
    dynamicCost: "echo",
    text: "Boss 第一阶段：从灵柩中取回 1 张牌。Boss 完成回响转化后：费用 0，回复 1 精神。",
    tags: ["消耗"],
    exhaust: true,
  },
  toxin: {
    name: "毒素",
    type: "skill",
    cost: 0,
    text: "虚无。打出：失去 2 生命。回合结束仍在手牌：失去 6 生命。",
    tags: ["虚无"],
    vanish: true,
  },
  junk: {
    name: "垃圾",
    type: "skill",
    cost: 0,
    text: "占据抽牌和手牌空间；回合结束进入弃牌堆。",
    tags: ["无法打出"],
    unplayable: true,
  },
  anxiety: {
    name: "焦虑",
    type: "skill",
    cost: 0,
    text: "回合结束失去 1 精神。",
    tags: ["无法打出", "虚无"],
    unplayable: true,
    vanish: true,
  },
  drowsiness: {
    name: "困意",
    type: "skill",
    cost: 0,
    text: "无法打出，虚无。在手牌中时，下一张攻击牌伤害 -4。",
    tags: ["无法打出", "消失"],
    unplayable: true,
    vanish: true,
  },
  overtake: {
    name: "弯道超车",
    type: "skill",
    cost: 0,
    text: "回复 1 精神。进入暑假：本回合不能打出攻击牌。",
    tags: ["保留"],
    retain: true,
  },
  last_stand: {
    name: "破釜沉舟",
    type: "skill",
    cost: 0,
    text: "失去所有精神。每失去 1 精神，获得 1 力量。",
    tags: ["消耗"],
    exhaust: true,
  },
  tower_shadow: {
    name: "塔影",
    type: "skill",
    cost: 0,
    text: "从灵柩中取回 1 张牌。",
    tags: ["保留"],
    retain: true,
  },
  todo: {
    name: "待完成",
    type: "skill",
    cost: 0,
    text: "无法打出，虚无。回合结束：失去 1 精神。若处于暑假，改为回复 1 精神。",
    tags: ["无法打出", "虚无"],
    unplayable: true,
    vanish: true,
  },
  lag: {
    name: "卡顿",
    type: "skill",
    cost: 0,
    text: "无法打出，虚无。回合结束：若未签到成功，失去 1 精神。",
    tags: ["无法打出", "虚无"],
    unplayable: true,
    vanish: true,
  },
};

export const SHOP_CARD_POOL = {
  common: [
    { key: "talk", cost: 1 },
    { key: "breathe", cost: 1 },
    { key: "rest", cost: 1 },
    { key: "boya", cost: 1 },
    { key: "torment", cost: 1 },
  ],
  build: [
    { key: "persuade", cost: 2 },
    { key: "reflect", cost: 2 },
    { key: "retreat", cost: 2 },
    { key: "one_tenth", cost: 2 },
    { key: "retake", cost: 2 },
    { key: "temporary", cost: 2 },
  ],
  rare: [
    { key: "insight", cost: 3, unlockAfterSite: "site_20" },
    { key: "overtake", cost: 3, unlockAfterSite: "site_20" },
    { key: "last_stand", cost: 3, unlockAfterSite: "site_20" },
  ],
};

export const STARTER_DECK_KEYS = [
  "talk",
  "talk",
  "3.92",
  "3.92",
  "persuade",
  "persuade",
  "breathe",
  "breathe",
  "reflect",
  "reflect",
  "retreat",
  "torment",
  "torment",
  "boya",
];

export const RELIC_DEFS = {
  soy_milk: {
    name: "半杯豆浆",
    text: "每场战斗开始时回复 1 精神。",
  },
  unfinished_homework: {
    name: "没写完的作业",
    text: "每场战斗第一次精神低于 5 时，抽 1 张牌。",
  },
  scratch_paper: {
    name: "草稿纸",
    text: "每场战斗第一次打出技能牌后，获得 3 防御。",
  },
  used_bottle: {
    name: "二手水杯",
    text: "每当你通过卡牌实际回复精神时，获得 4 防御。",
  },
  old_campus_card: {
    name: "旧校园卡",
    text: "每次书架刷新后的第一次手动刷新免费。",
  },
  borrowed_umbrella: {
    name: "借来的伞",
    text: "若你回合内没有打出攻击牌，回合结束获得 6 防御。",
  },
  wrong_notebook: {
    name: "错题本",
    text: "每场战斗第一次打出重修时，抽牌数 +1。",
  },
  folding_chair: {
    name: "折叠椅",
    text: "每回合第一次获得防御时，额外获得 6 防御。",
  },
  expired_coffee: {
    name: "过期咖啡",
    text: "每场战斗开始时回复 3 精神并获得 1 力量。第 3 回合开始时失去 1 精神。",
  },
  campus_net_auth: {
    name: "校园网认证",
    text: "如果你回合开始时精神至少为 8，获得 1 敏捷。",
  },
  lecture_album: {
    name: "讲座纪念册",
    text: "每当你进入暑假，抽 1 张牌并获得 6 防御，每回合限 1 次。",
  },
  lost_found_slip: {
    name: "失物招领单",
    text: "每场战斗第一次有牌进入弃牌堆以外区域时，回复 1 精神。",
  },
  auto_checkin_script: {
    name: "自动签到脚本",
    text: "每施加第 3 层注视时，回复 1 精神。",
  },
  gpa_calculator: {
    name: "绩点计算器",
    text: "你的【3.92】额外造成 2 点伤害。每场战斗第一次打出【3.92】时，获得 1 力量。",
  },
  empty_classroom: {
    name: "空教室",
    text: "回合结束时，若精神高于 8，回复 3 生命。",
  },
  old_clock: {
    name: "旧钟表",
    text: "每 3 回合，玩家回合开始时回复 1 精神。",
  },
  course_selection: {
    name: "选课系统",
    text: "每场战斗开始时，从 3 张随机牌中选 1 张加入手牌，该牌本回合费用 -1。",
  },
  extension_request: {
    name: "延期申请",
    text: "每场战斗第一次受到致命伤害时，保留 1 生命，并失去所有精神。",
  },
  boya_shadow: {
    name: "博雅塔剪影",
    text: "每场战斗第一次进入暑假时，回复 2 精神，并获得 8 防御。",
  },
  graduate_list: {
    name: "保研名单",
    text: "每场战斗开始时获得 1 力量、1 敏捷，但最大精神 -1。",
  },
  unsubmitted_application: {
    name: "未提交的申请",
    text: "每当你打出费用至少为 2 的牌，获得 1 力量。",
  },
  dorm_earplug: {
    name: "宿舍耳塞",
    text: "每场战斗第一次失去精神时，改为不失去，并获得 6 防御。",
  },
};

export const ADVANCED_RELIC_POOL = [
  "wrong_notebook",
  "folding_chair",
  "lost_found_slip",
  "expired_coffee",
  "dorm_earplug",
  "campus_net_auth",
  "lecture_album",
  "auto_checkin_script",
];

export const EVENT_DEFS = {
  event_auditorium: {
    title: "事件：大礼堂",
    background: "./assets/scenes/stage_09/bg.png",
    text: "你走进大礼堂。来自台上的声音被扩音器拉得狭长，像一张挤入门缝中的、修饰过度的简历。每个人都在等待一个宏大的答案。",
    choices: [
      { label: "坐在最后一排", detail: "回复 20 生命与 3 精神", effects: [{ type: "gainHp", amount: 20 }, { type: "gainMental", amount: 3 }] },
      { label: "认真听完", detail: "获得 1 张弯道超车", effects: [{ type: "addCard", key: "overtake" }] },
      { label: "讲的什么玩意？", detail: "回复 8 生命，获得 1 张 1/10", effects: [{ type: "gainHp", amount: 8 }, { type: "addCard", key: "one_tenth" }] },
    ],
  },
  event_85km: {
    title: "85 km",
    background: "./assets/scenes/stage_22/bg.png",
    text: "本学期要求累计跑步：85.00 km\n当前完成：72.40 km\n剩余：12.60 km\n截止时间：明晚 23:59\n\n操场的灯已经亮了。",
    choices: [
      { label: "认真补跑", quote: "至少这次还是认真一下。", detail: "回复 5 精神。获得 1 张休整。", effects: [{ type: "gainMental", amount: 5 }, { type: "addCard", key: "rest" }] },
      { label: "分段规划", quote: "明天开始，每天一点。", detail: "获得 1 张弯道超车与 1 张待完成。", effects: [{ type: "addCard", key: "overtake" }, { type: "addCard", key: "todo" }] },
      { label: "压线夜跑", quote: "没事。最后二十分钟，我直接解决所有问题。", detail: "获得 2 件随机进阶遗物。将 1 张焦虑加入牌堆。", effects: [{ type: "gainRandomAdvancedRelics", count: 2 }, { type: "addCard", key: "anxiety" }] },
      { label: "利用定位漂移", quote: "轨迹开始变得很有想象力。", detail: "删除 1 张牌。获得 1 张洞见。", effects: [{ type: "removeCard" }, { type: "addCard", key: "insight" }] },
    ],
  },
  event_boya_tower: {
    title: "事件：博雅塔",
    background: "./assets/scenes/stage_18/bg.png",
    text: "你走到博雅塔前。夜色把塔身拉得像一支没有写完的笔。",
    choices: [
      { label: "休息", detail: "回复 30 生命和 1 精神。下场战斗开局获得 6 防御。", effects: [{ type: "gainHp", amount: 30 }, { type: "gainMental", amount: 1 }, { type: "gainNextBattleBlock", amount: 6 }] },
      { label: "整理书包", detail: "删除至多 2 张牌，回复 2 精神", effects: [{ type: "removeUpToCards", count: 2 }, { type: "gainMental", amount: 2 }] },
      { label: "凝望塔影", detail: "获得 1 张塔影。最大精神 -1。", effects: [{ type: "addCard", key: "tower_shadow" }, { type: "loseMaxMental", amount: 1 }] },
      { label: "靠着塔睡着", detail: "回复所有生命，但失去所有精神。获得 1 张焦虑", effects: [{ type: "healFull" }, { type: "loseAllMental" }, { type: "addCard", key: "anxiety" }] },
    ],
  },
};

export const BATTLE_DEFS = {
  stage_08: {
    background: "./assets/scenes/stage_08/bg.png",
    corruptedBackground: "./assets/scenes/stage_08/bg_1.png",
    enemyName: "签到",
    enemyImages: ["./assets/scenes/stage_08/enemy.png"],
    hp: 130,
    mechanics: "checkin",
    rewardPool: [
      "auto_checkin_script",
      "gpa_calculator",
      "lecture_album",
      "empty_classroom",
      "old_clock",
      "course_selection",
      "folding_chair",
      "campus_net_auth",
    ],
    pattern: [
      {
        id: "loading",
        name: "加载中",
        damage: 12,
        intent: "攻击 12 / 卡顿",
        message: "加载中",
        addDiscard: "lag",
      },
      {
        id: "qr_offset",
        name: "扫码框偏移",
        hits: [8, 8],
        intent: "攻击 8x2",
        message: "扫码框偏移",
      },
      {
        id: "network_wave",
        name: "网络波动",
        block: 22,
        intent: "防御 22 / 卡顿 / 网络波动",
        message: "网络波动",
        addDraw: "lag",
        scanNextAdjustment: -1,
      },
      {
        id: "face_check",
        name: "人脸识别",
        damage: 20,
        intent: "攻击 20",
        message: "人脸识别",
        loseMentalIfBelow: { threshold: 5, amount: 1 },
        addAnxietyIfMentalAbove: 7,
      },
    ],
  },
  stage_13: {
    background: "./assets/scenes/stage_13/bg.png",
    corruptedBackground: "./assets/scenes/stage_13/bg-1.png",
    enemyName: "混乱闹钟",
    enemyImages: ["./assets/scenes/stage_13/enemy.png"],
    hp: 70,
    mechanics: "earlyMorning",
    rewardPool: ["soy_milk", "unfinished_homework", "scratch_paper", "used_bottle", "old_campus_card", "borrowed_umbrella"],
    pattern: [
      {
        id: "prepare_bell",
        name: "7:57 预备铃",
        damage: 10,
        intent: "攻击 10",
        message: "还有三分钟。",
      },
      {
        id: "alarm_vibrate",
        name: "7:58 闹铃震动",
        hits: [7, 7],
        intent: "攻击 7x2",
        message: "你听见了，但你没有动。",
      },
      {
        id: "late_feeling",
        name: "7:59 迟到预感",
        block: 15,
        status: "late",
        intent: "防御 15 / 迟到",
        message: "再不起就来不及了。",
      },
      {
        id: "roll_call",
        name: "8:00 点名",
        damage: 24,
        intent: "攻击 24",
        message: "你为什么又没来？",
      },
    ],
  },
  stage_20: {
    background: "./assets/scenes/stage_20/bg.png",
    corruptedBackground: "./assets/scenes/stage_20/bg_1.png",
    enemyName: "你的抖腿前桌",
    enemyImages: [
      "./assets/scenes/stage_20/enemy_layer1.png",
      "./assets/scenes/stage_20/enemy_layer2.png",
    ],
    hp: 115,
    mechanics: "legShake",
    rewardPool: ["wrong_notebook", "folding_chair", "expired_coffee", "campus_net_auth", "lecture_album", "scratch_paper"],
    textureInterval: 1000,
    pattern: [
      {
        id: "small_shake",
        name: "小幅抖动",
        damage: 10,
        intent: "攻击 10",
        message: "哒、哒、哒、哒。",
      },
      {
        id: "pencil_fall",
        name: "铅笔滚落",
        intent: "塞垃圾 / 分心",
        message: "你的笔滚到了地上。",
        addDraw: "junk",
        status: "distracted",
      },
      {
        id: "desk_collapse",
        name: "桌洞坍塌",
        hits: [7, 7],
        intent: "攻击 7x2",
        message: "桌洞里的东西全都涌了出来。",
        junkDamage: true,
      },
    ],
  },
  stage_04: {
    background: "./assets/scenes/stage_04/bg.png",
    corruptedBackground: "./assets/scenes/stage_04/bg_1.png",
    mechanics: "dorm",
    rewardPool: ["extension_request", "boya_shadow", "graduate_list", "unsubmitted_application", "old_clock", "course_selection"],
    rewardCards: ["temporary", "retake", "torment", "rest", "insight", "one_tenth", "overtake"],
    enemies: [
      {
        id: "smell",
        name: "臭味怪",
        enemyImages: ["./assets/scenes/stage_04/enemy_1.png"],
        hp: 50,
        environmentKey: "smell",
        deathMessage: "空气终于清了一点。\n你听见剩下的声音更响了，地上的东西也显得更多了。",
        pattern: [
          { id: "ferment", name: "外卖发酵", intent: "毒素入手", message: "你确定这个还能吃吗？", addHand: "toxin" },
          { id: "choke", name: "呛鼻气味", damage: 7, intent: "攻击 7", message: "别呼吸。" },
          { id: "spread", name: "扩散", intent: "垃圾入弃牌堆", message: "味道只是换了个地方。", addDiscard: "junk" },
        ],
      },
      {
        id: "noise",
        name: "噪声怪",
        enemyImages: ["./assets/scenes/stage_04/enemy_2.png"],
        hp: 45,
        environmentKey: "noise",
        deathMessage: "宿舍安静了一瞬。\n沉默让气味更加明显，也让堆积物更加无处可逃。",
        pattern: [
          { id: "video", name: "外放短视频", hits: [4, 4], intent: "攻击 4x2", message: "外放怎么了？" },
          { id: "loop", name: "循环播放", intent: "下回合技能减半", message: "这段我再放一遍。", nextSkillHalf: true },
          { id: "crack", name: "破音", intent: "失去 1 精神", message: "——刺啦！", loseMental: 1 },
        ],
      },
      {
        id: "clutter",
        name: "堆积怪",
        enemyImages: ["./assets/scenes/stage_04/enemy_3.png"],
        hp: 65,
        environmentKey: "clutter",
        deathMessage: "地面终于露了出来。\n没有东西挡着之后，味道和噪声都直接冲向了你。",
        pattern: [
          { id: "pile_up", name: "堆起来", intent: "全体防御 6", message: "先放这儿。", blockAll: 6 },
          { id: "collapse", name: "倒塌", damage: 14, intent: "攻击 14", message: "小心！" },
          { id: "pressure", name: "压迫空间", damage: 8, intent: "攻击 8 / 垃圾入弃牌堆", message: "这里本来就不该有这么多东西。", addDiscard: "junk" },
        ],
      },
    ],
  },
  stage_23: {
    background: "./assets/scenes/stage_23/bg.png",
    corruptedBackground: "./assets/scenes/stage_23/bg-1.png",
    mechanics: "coffinBoss",
    enemyName: "理想的灵柩",
    enemyImages: ["./assets/scenes/stage_23/boss_A.png"],
    phaseTwoImages: [
      "./assets/scenes/stage_23/boss_B_layer1.png",
      "./assets/scenes/stage_23/boss_B_layer2.png",
    ],
    coffinImage: "./assets/scenes/stage_23/coffin.png",
    hp: 300,
    textureInterval: 1000,
    pattern: [
      {
        id: "ideal_seal",
        name: "理想封存",
        damage: 15,
        coffinBonus: true,
        intent: "攻击 / 封存",
        message: "先把不必要的部分收起来。",
        sealHandCard: true,
        addHand: "call",
      },
      {
        id: "abyss_invite",
        name: "深渊邀约",
        damage: 15,
        intent: "攻击 / 空洞",
        message: "空出来的位置，总要由别的东西填上。",
        hollow: 2,
      },
    ],
  },
};
